[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.4",
    "pandas>=3.0.3",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.2",
    "rasterio>=1.4.3",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "shapely>=2.1.2",
    "tenacity>=9.1.4",
    "tqdm>=4.68.4",
]
